Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'

    # Test a forward normal mount: 
    #     mounting a folder from a 3rd party host into guest
    config.vm.synced_folder "/etc/", "/tmp/forward_normal_mount_etc/", type: "sshfs",
        ssh_host: ENV['THIRD_PARTY_HOST'],
        ssh_username: ENV['THIRD_PARTY_HOST_USER'],
        ssh_password: ENV['THIRD_PARTY_HOST_PASS']

    # Test a forward slave mount: 
    #   mounting /etc/ from the vagrant host into the guest
    config.vm.synced_folder "/etc/", "/tmp/forward_slave_mount_etc/", type: "sshfs"

    # Test a reverse mount:
    # mounting /etc/ from vagrant guest into vagrant host
    config.vm.synced_folder "/tmp/reverse_mount_etc/", "/etc", type: "sshfs", reverse: true

    host = 'vagrant-sshfs-tests'
    box  = 'fedora/24-cloud-base'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
    end
end
