# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# XXX Note this is not working right now as nested virt. I keep
# getting kernel tracebacks on Fedora 24.
#
Vagrant.configure(2) do |config|

  config.ssh.insert_key = 'true'
  config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"

  config.vm.provider :libvirt do |domain|
    domain.memory = 4096
    domain.cpus = 4
    domain.nested = true
  end

  host = 'viv-virtbox' # vagrant in vagrant - to test virtbox
  box  = 'fedora/24-cloud-base'

  config.vm.define host do | tmp |
      tmp.vm.hostname = host
      tmp.vm.box = box
  end
  # Must use VirtualBox-5.0 - 5.1 not supported by Vagrant yet
  config.vm.provision "shell", inline: <<-SHELL
    dnf config-manager --add-repo http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    rpms=(
      kernel-devel-$(uname -r) kernel-headers-$(uname -r)
      gcc make VirtualBox-5.0                    # all for virtualbox support
      make gcc ruby ruby-devel redhat-rpm-config # for building gems
      gcc-c++                                    # for building unf_ext
      libvirt-devel                              # for building ruby-libvirt gem
      zlib-devel                                 # for building nokogiri gem
      git                                        # for the git ls-files in gemspec file
      bsdtar                                     # used by vagrant to unpack box files
    )
    dnf install -y ${rpms[@]}
    /usr/lib/virtualbox/vboxdrv.sh setup
    usermod -a -G vboxusers vagrant
  SHELL
end
